defaults:
  - _self_

# Override experiment-specific settings here
experiments:
  name: "posebusters"
  sdf_regex: ".*ligand.sdf$"                          # default path containing "ligand" ending in ".sdf"
  # ref_sdf_regex: "reference\\.sdf"   # optional: in each folder use matching SDF for pocket definition

# GLOBAL SETTINGS
seed: 0
run_tag: conformer_sampling
output_dir: null  # output directory for sampling results (will be created if it doesn't exist)
num_seeds: 1 # MUST be 1 for full reproducibility.

# Hydra settings (disable outputs/...)
hydra:
  run:
    dir: .               # stay in current working dir
  output_subdir: null    # don't create .hydra with config copies

hardware:
  devices: [0] # device to use (cuda or cpu)
  accelerator: auto
  strategy: auto
  precision: 32  # precision to use (32, 16, or bf16)
  deterministic: true  # whether to use deterministic training/inference for reproducibility
  cuda_precision: high

graph:
  fragmentation_strategy: canonical  # fragmentation strategy for ligands (canonical, random, smallest)
  sample_conformer: true  # whether to fragments from sample conformers at inference or use bound pose fragments
  alignment_tries: 0  # number of tries to align the ligand conformer to the bound pose, only if sample_conformers is false
  pocket_distance_cutoff: 6.0  # distance cutoff for defining pocket residues
  pocket_com_noise: 0.25
  pocket_distance_noise: 0.5
  pocket_coordinate_jitter: 0.02
  random_rotation: false  # whether to apply a random rotation to the complex
  use_esm_embeddings: false
  ignore_conjugated_torsion: false # whether to ignore conjugated bonds when defining rotatable bonds
  ignore_triangulation: false # whether to ignore triangulation when defining rotatable bonds

diffusion:
  num_steps: 30 # number of diffusion steps
  t_min: 0.002  # minimum noise level (see Karras et al. 2022)
  rho: 3.0 # controls the spacing of the noise schedule (see Karras et al. 2022)
  noise_scale: 0.0  # scale of the noise to add at each step (0=no noise better fidelity, 1=full noise better diversity)
  noise_decay: 2.0 # controls the decay of the noise schedule (annealed)
  discretization: edm  # discretization method for noise schedule (power or edm)
  solver: euler  # solver to use for reverse diffusion (euler or heun)
  use_true_scores: false  # whether to use true scores (if available) instead of learned scores (for evaluation only)
  verbose: false  # whether to print verbose output during sampling

data:
  batch_size: 32  # batch size for sampling
  num_workers: 4  # number of workers for data loading
  data_dir: "/data/ziz/not-backed-up/datasets-ziz-all/SigmaDock/data/"
  blacklist: "/data/ziz/not-backed-up/datasets-ziz-all/SigmaDock/data/posebusters_paper/posebusters_correct_ids.txt"

model:
  model_id: null # Defaults to ckpt_dir stem if None
  ckpt_dir: "/vols/ziz/not-backed-up/scratch/sigmadock/paper/model_0.ckpt"  # path to checkpoint to load. Must be specified.
  cached_s03_dir: sigmadock/diff/cache
  use_ema: true  # whether to use EMA model for sampling

postprocessing:
  scoring: vinardo  # "vina" or "vinardo" to compute gnina scores. Null to ignore.
  bust_config: redock  # redock or none to ignore PB checks.